version: build-{build}.{branch}
image: Previous Visual Studio 2022

build_script:
  - pwsh: |
      wsl -l -v
      wsl --install
      wsl --help
      curl.exe -SL https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe -O
      ls
      pwd
      Start-Process '.\Docker Desktop Installer.exe' -Wait 'install','--accept-license'
